### ISSUE TITLE
[error] Method is not present on Selenium interface: while

### ISSUE THREAD

**Issue by pumamammal** [davehunt/selenium-ide-flowcontrol#6]
i tried using FlowControl with the latest version of Selenium IDe and i get this error
 
`[error] Method is not present on Selenium interface: while`

I guess its not working, I tried with version Selenium 1.0.5 it worked only with the mozilla version 3.5 which it so outdated..

anyone here know what I could do?

**Comment by davehunt** [comment]
I'm no longer maintaining this add-on. Anyone is welcome to fork and continue to work on it.
